development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://fayeserver.herokuapp.com/faye"  
  secret_token: "sec-c-MTU5MGZhZDEtZTZhMy00NTdiLTk3ZWYtNzc2MjRiM2RjODAz"
  signature_expiration: 86400 # one hour
